export const themeColors = {
  primary: "var(--primary)",
  primaryMedium: "#b4e4ce",
  primaryLight: "#f7fcfa",
  secondary: "#ff227d",
  accent: "#797bf2",
  accentMedium: "#d4b3ff",
  accentLight: "#b8ccff",
  success: "var(--success)",
  info: "var(--info)",
  warning: "var(--warning)",
  danger: "var(--danger)",
  purple: "#8269B2",
  blue: "#37C3FF",
  green: "#93E088",
  yellow: "#FFD66E",
  orange: "#FFA981",
  lightText: "#a2a5b9",
  fadeGrey: "#ededed",
};
